### ISSUE TITLE
这个与 使用Vue , vue.esm.js动态编译的优势在哪呢.

### ISSUE THREAD

**Issue by angelbi** [bug4j/vue-cdn-component-loader#4]
最近有个字符串组件的需求
let hello = Vue.component('Hello', {
     template:'<div class="is-size-1">Hello Word</div>',
})
因为Vue默认是运行时编译，所以无法正常创建组件
但可以改变webpack编译方式 vue.esm.js来解决这个问题
So! 你这个优势在哪呢.

**Comment by bug4j** [comment]
这个工具的目的就是去掉webpack,应为我有一个很脑残的领导希望后端人员也能立马上手
